[package]
name = "mesh-testing"

version = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cw-multi-test   = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true, features = ["ibc3"] }
schemars        = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }

meta-staking  = { workspace = true }
mesh-consumer = { workspace = true }
