[workspace]
members = ["packages/*", "contracts/*"]

[profile.release.package.mesh-consumer]
codegen-units = 1
incremental = false

[profile.release.package.mesh-lockup]
codegen-units = 1
incremental = false

[profile.release.package.mesh-provider]
codegen-units = 1
incremental = false

[profile.release.package.mesh-slasher]
codegen-units = 1
incremental = false

[profile.release.package.meta-staking]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
